# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 488)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label10 = QtWidgets.QLabel(self.centralwidget)
        self.label10.setGeometry(QtCore.QRect(20, 380, 131, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label10.setFont(font)
        self.label10.setObjectName("label10")
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(20, 340, 131, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 22, 91, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        self.label8.setGeometry(QtCore.QRect(20, 300, 141, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.line1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(160, 20, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line1.setFont(font)
        self.line1.setObjectName("line1")
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setGeometry(QtCore.QRect(20, 260, 111, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(20, 220, 111, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(20, 140, 91, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(20, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(20, 180, 91, 21))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.line2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(160, 60, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line2.setFont(font)
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QLineEdit(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(160, 100, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line3.setFont(font)
        self.line3.setObjectName("line3")
        self.line4 = QtWidgets.QLineEdit(self.centralwidget)
        self.line4.setGeometry(QtCore.QRect(160, 140, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line4.setFont(font)
        self.line4.setObjectName("line4")
        self.line5 = QtWidgets.QLineEdit(self.centralwidget)
        self.line5.setGeometry(QtCore.QRect(160, 180, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line5.setFont(font)
        self.line5.setObjectName("line5")
        self.line6 = QtWidgets.QLineEdit(self.centralwidget)
        self.line6.setGeometry(QtCore.QRect(160, 220, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line6.setFont(font)
        self.line6.setObjectName("line6")
        self.line7 = QtWidgets.QLineEdit(self.centralwidget)
        self.line7.setGeometry(QtCore.QRect(160, 260, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line7.setFont(font)
        self.line7.setObjectName("line7")
        self.line8 = QtWidgets.QLineEdit(self.centralwidget)
        self.line8.setGeometry(QtCore.QRect(160, 300, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line8.setFont(font)
        self.line8.setObjectName("line8")
        self.line9 = QtWidgets.QLineEdit(self.centralwidget)
        self.line9.setGeometry(QtCore.QRect(160, 340, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line9.setFont(font)
        self.line9.setObjectName("line9")
        self.line10 = QtWidgets.QLineEdit(self.centralwidget)
        self.line10.setGeometry(QtCore.QRect(160, 380, 241, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.line10.setFont(font)
        self.line10.setObjectName("line10")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 430, 75, 23))
        font = QtGui.QFont()
        font.setFamily("ms gothic")
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        # MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.msg)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DemooPlayer Txt Builder"))
        self.label10.setText(_translate("MainWindow", "OFFSET"))
        self.label9.setText(_translate("MainWindow", "PIANOVOLUME"))
        self.label1.setText(_translate("MainWindow", "JSON"))
        self.label8.setText(_translate("MainWindow", "AUDIOVOLUME"))
        self.label2.setText(_translate("MainWindow", "AUDIO"))
        self.line1.setText(_translate("MainWindow", "hard.json"))
        self.label7.setText(_translate("MainWindow", "LEVEL"))
        self.label6.setText(_translate("MainWindow", "DIFFICULTY"))
        self.label4.setText(_translate("MainWindow", "TITLE"))
        self.label3.setText(_translate("MainWindow", "COVER"))
        self.label5.setText(_translate("MainWindow", "COMPOSER"))
        self.line2.setText(_translate("MainWindow", "music.mp3"))
        self.line3.setText(_translate("MainWindow", "cover.png"))
        self.line6.setText(_translate("MainWindow", "2"))
        self.line7.setText(_translate("MainWindow", "10"))
        self.line8.setText(_translate("MainWindow", "100"))
        self.line9.setText(_translate("MainWindow", "0"))
        self.line10.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
